parameters:
    serpapi.key: '%env(SERPAPI_KEY)%'
    flight.default_origin: '%env(FLIGHT_DEFAULT_ORIGIN)%'
    abstract_holidays.api_key: '%env(ABSTRACT_HOLIDAYS_API_KEY)%'
    unsplash.access_key: '%env(UNSPLASH_ACCESS_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\AmadeusFlightService:
        arguments:
            $apiKey: '%serpapi.key%'
            $defaultOrigin: '%flight.default_origin%'

    App\Service\HolidayService:
        arguments:
            $apiKey: '%abstract_holidays.api_key%'
            $cacheDir: '%kernel.cache_dir%'

    App\Service\UnsplashService:
        arguments:
            $accessKey: '%unsplash.access_key%'
